/**
 * GET /api/course-builder/probe-publish?location=...
 *
 * Auth-isolated probe: runs the exact same getAuthForLocation() logic the
 * publisher uses, then issues a tiny bulk-import payload, then returns
 * status + first 800 bytes of the body. Lets us debug auth + endpoint
 * without burning Groq tokens.
 *
 * CRON_SECRET-gated. Allow-listed locations only.
 */
import { NextRequest, NextResponse } from 'next/server'
import { getAuthForLocation } from '@/lib/crm'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const CRM_BASE = 'https://services.leadconnectorhq.com'
const CRM_VERSION = '2021-07-28'

const ALLOWED = new Set([
  'nphConTwfHcVE1oA0uep',
  '6MSqx0trfxgLxeHBJE1k',
  'AeY8M0GNOuJPNkLQ7AAC',
  'Ev1Bzj84a2vljzCkfBEM',
  'F76MNKOMQCMruMrumtdf',
])

export async function GET(req: NextRequest) {
  const url = new URL(req.url)
  const provided =
    req.headers.get('authorization')?.replace(/^Bearer\s+/i, '') ||
    url.searchParams.get('secret') ||
    ''
  if (!process.env.CRON_SECRET || provided !== process.env.CRON_SECRET) {
    return NextResponse.json({ ok: false, error: 'unauthorized' }, { status: 401 })
  }

  const locationId = url.searchParams.get('location') || 'nphConTwfHcVE1oA0uep'

  /**
   * DRY MODE — resolve the credential and stop.
   *
   * The write probe is allow-listed to five 0n-owned locations because it
   * creates a real course in a real account. That allow-list also made the
   * probe useless for the question that actually blocked Course Builder on
   * 2026-08-20: "can we get a token for THIS agency sub-account?" — a
   * read-only question about accounts that are, by definition, not on the
   * list. `?dry=1` answers exactly that and writes nothing, so it is safe for
   * any location the CRON_SECRET holder already has agency rights over.
   */
  const dry = url.searchParams.get('dry') === '1'
  if (!dry && !ALLOWED.has(locationId)) {
    return NextResponse.json({ ok: false, error: 'location_not_allowed' }, { status: 400 })
  }

  // Step 1: resolve auth
  const auth = await getAuthForLocation(locationId)
  const tokenPreview = auth.token
    ? `${auth.token.slice(0, 12)}…${auth.token.slice(-6)}`
    : '(EMPTY)'

  if (dry) {
    return NextResponse.json({
      ok: Boolean(auth.token),
      dry: true,
      locationId,
      resolved: Boolean(auth.token),
      source: auth.source,
      installId: auth.installId ?? null,
      tokenPreview,
      unresolved: auth.unresolved ?? null,
    })
  }

  // Step 2: minimal bulk-import payload — same shape the publisher uses
  const payload = {
    locationId,
    products: [
      {
        title: `PROBE — DELETE ME ${new Date().toISOString().slice(0, 19)}`,
        description: 'Auth probe from /api/course-builder/probe-publish.',
        instructorDetails: {
          name: '0n Course Builder',
          description: 'AI-generated by the 0n Course Builder app.',
        },
        categories: [
          {
            title: 'Course Content',
            visibility: 'published',
            posts: [
              {
                title: 'Probe lesson',
                visibility: 'published',
                contentType: 'video',
                description: 'Probe content.',
              },
            ],
          },
        ],
      },
    ],
  }

  const t0 = Date.now()
  const res = await fetch(`${CRM_BASE}/courses/courses-exporter/public/import`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${auth.token}`,
      Version: CRM_VERSION,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  })
  const elapsed = Date.now() - t0
  const text = await res.text()

  return NextResponse.json({
    ok: res.ok,
    status: res.status,
    elapsed_ms: elapsed,
    auth: { source: auth.source, locationId: auth.locationId, tokenPreview },
    response_body: text.slice(0, 1500),
  })
}
