export interface MarketplaceAddon {
  slug: string
  name: string
  shortDesc: string
  longDesc: string
  price: number // cents
  priceLabel: string
  categories: string[]
  capabilities: string[]
  requiredPlan: 'free' | 'starter' | 'professional' | 'unlimited'
  badge?: string
  features: string[]
  integrations: string[]
  relatedAddons: string[]
}

export interface MarketplaceCategory {
  slug: string
  name: string
  description: string
  count: number
  icon: string
  color: string
}

export const CATEGORIES: MarketplaceCategory[] = [
  { slug: '0n-crm', name: '0n CRM', description: 'Core CRM capabilities — contacts, pipeline, invoices, payments, calendars, and location settings.', count: 6, icon: 'database', color: '#a78bfa' },
  { slug: 'marketing', name: 'Marketing', description: 'Social media, email campaigns, content creation, funnels, and ad management.', count: 6, icon: 'megaphone', color: '#00d4ff' },
  { slug: 'ai-automation', name: 'AI & Automation', description: 'Voice AI, course builder, agent studio, conversation AI, and workflow intelligence.', count: 6, icon: 'brain', color: '#7ed957' },
  { slug: 'analytics', name: 'Analytics', description: 'Reporting, tracking, link triggers, ad-click grading, conversion optimization, and brand management.', count: 6, icon: 'chart', color: '#fbbf24' },
  { slug: 'communication', name: 'Communication', description: 'Phone system, documents, contracts, and messaging.', count: 3, icon: 'phone', color: '#14b8a6' },
  { slug: 'sales', name: 'Sales', description: 'Affiliate programs, product catalog, e-commerce, and deal tracking.', count: 4, icon: 'dollar', color: '#f97316' },
  { slug: 'content', name: 'Content', description: 'Forms, landing pages, media management, WordPress, and brand design kits.', count: 5, icon: 'pencil', color: '#ec4899' },
  { slug: 'admin', name: 'Admin', description: 'Snapshots, SaaS management, user roles, custom objects, and location settings.', count: 5, icon: 'settings', color: '#6b7280' },
]

export const ADDONS: MarketplaceAddon[] = [
  // === FEATURED ===
  {
    slug: 'content-engine',
    name: 'Content Engine',
    shortDesc: 'AI writes blogs, posts to social, sends email campaigns — all from one conversation.',
    longDesc: 'The Content Engine combines three powerful capabilities into a single add-on: AI blog generation, multi-platform social posting, and email campaign management. Tell the AI what you want to write, and it handles the rest — from drafting to publishing. Powered by Groq for lightning-fast generation.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['marketing', 'ai-automation'],
    capabilities: ['blog_create', 'social_post_create', 'social_post_schedule', 'email_template_create', 'email_send'],
    requiredPlan: 'starter',
    badge: 'NEW',
    features: [
      'AI blog post generation (Groq-powered)',
      'Multi-platform social posting (Facebook, Instagram, LinkedIn, X, TikTok)',
      'Bulk post generator (50+ posts from topics)',
      'CSV import/export for mass scheduling',
      'AI email campaign generation',
      'CRM contact segmentation for targeted sends',
      'Conversation-driven — just tell the AI what to write',
    ],
    integrations: ['CRM Social Planner', 'CRM Email Builder', 'CRM Contacts', 'Groq AI'],
    relatedAddons: ['social-planner', 'email-builder', 'blog-engine'],
  },
  // === AI & AUTOMATION ===
  {
    slug: 'ai-course-builder',
    name: 'AI Course Builder',
    shortDesc: 'Generate full courses with AI and import directly into your CRM.',
    longDesc: 'Create complete online courses with AI-generated lessons, quizzes, and instructor profiles. The Course Builder integrates directly with your CRM membership area, so students can enroll and progress through content automatically.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['ai-automation', 'content'],
    capabilities: ['course_create', 'lesson_generate', 'instructor_profile', 'membership_import'],
    requiredPlan: 'starter',
    features: [
      'AI lesson generation with structured curriculum',
      'Auto-import to CRM membership area',
      'Instructor profile management',
      'Quiz and assessment creation',
      'Student progress tracking',
    ],
    integrations: ['CRM Memberships', 'Groq AI', 'CRM Contacts'],
    relatedAddons: ['conversation-ai', 'knowledge-base', 'content-engine'],
  },
  {
    slug: 'voice-ai-agent',
    name: 'Voice AI Agent',
    shortDesc: 'Deploy AI phone agents with knowledge bases and call routing.',
    longDesc: 'Set up intelligent voice agents that handle inbound and outbound calls. Each agent connects to your knowledge base for accurate responses, routes calls based on intent, and logs every interaction in your CRM for follow-up.',
    price: 9900,
    priceLabel: '$99/mo',
    categories: ['ai-automation', 'communication'],
    capabilities: ['voice_agent_create', 'call_routing', 'kb_integration', 'call_analytics'],
    requiredPlan: 'professional',
    badge: 'Pro',
    features: [
      'Inbound and outbound AI calling',
      'Knowledge base integration for accurate answers',
      'Intelligent call routing and transfers',
      'Call analytics and transcription',
      'CRM contact auto-logging',
    ],
    integrations: ['CRM Phone', 'CRM Contacts', 'Knowledge Base', 'CRM Conversations'],
    relatedAddons: ['conversation-ai', 'knowledge-base', 'phone-system'],
  },
  {
    slug: 'conversation-ai',
    name: 'Conversation AI',
    shortDesc: 'AI chatbots for messaging with custom personas.',
    longDesc: 'Deploy AI-powered chatbots across all your messaging channels. Create custom personas, set handoff rules, and let AI handle the first response while routing complex queries to your team.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['ai-automation', 'communication'],
    capabilities: ['chatbot_create', 'persona_config', 'handoff_rules', 'multi_channel_chat'],
    requiredPlan: 'starter',
    features: [
      'Multi-channel chat (SMS, web, social)',
      'Custom AI personas and tone',
      'Smart handoff to human agents',
      'Conversation history and analytics',
      'Auto-tagging and CRM updates',
    ],
    integrations: ['CRM Conversations', 'CRM Contacts', 'Knowledge Base'],
    relatedAddons: ['voice-ai-agent', 'knowledge-base', 'phone-system'],
  },
  {
    slug: 'agent-studio',
    name: 'Agent Studio Pro',
    shortDesc: 'Build and deploy AI agents with MCP tool access.',
    longDesc: 'The most powerful add-on in the marketplace. Agent Studio Pro gives you a visual builder for creating AI agents that can access all 335+ tools in the 0nMCP ecosystem. Wire up knowledge bases, define workflows, and deploy agents that work 24/7.',
    price: 9900,
    priceLabel: '$99/mo',
    categories: ['ai-automation'],
    capabilities: ['agent_create', 'tool_access', 'kb_wiring', 'workflow_builder'],
    requiredPlan: 'professional',
    badge: 'Pro',
    features: [
      'Visual agent creation interface',
      'Access to 335+ MCP tools',
      'Knowledge base wiring',
      'Custom workflow triggers',
      'Agent performance analytics',
    ],
    integrations: ['0nMCP SDK', 'CRM Agent Studio', 'Knowledge Base', 'CRM Workflows'],
    relatedAddons: ['knowledge-base', 'voice-ai-agent', 'workflow-reader'],
  },
  {
    slug: 'knowledge-base',
    name: 'Knowledge Base',
    shortDesc: 'Create AI knowledge bases for agents and bots.',
    longDesc: 'Upload documents, websites, and FAQs to create rich knowledge bases that power your AI agents and chatbots. Auto-training ensures your AI always has the latest information.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['ai-automation'],
    capabilities: ['kb_create', 'document_upload', 'agent_integration', 'auto_training'],
    requiredPlan: 'starter',
    features: [
      'Document and URL upload',
      'Agent and chatbot integration',
      'Auto-training on new content',
      'Embedding-based search',
      'Version management',
    ],
    integrations: ['CRM Agent Studio', 'Conversation AI', 'Voice AI Agent'],
    relatedAddons: ['agent-studio', 'conversation-ai', 'voice-ai-agent'],
  },
  // === MARKETING ===
  {
    slug: 'social-planner',
    name: 'Social Planner',
    shortDesc: 'Connect social accounts and publish AI-generated content.',
    longDesc: 'Connect your Google Business, Facebook, Instagram, and LinkedIn accounts. Schedule posts, track engagement, and let AI generate content optimized for each platform.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['marketing'],
    capabilities: ['social_connect', 'post_schedule', 'analytics_social', 'ai_content_gen'],
    requiredPlan: 'starter',
    features: [
      'Google, Facebook, Instagram, LinkedIn integration',
      'Post scheduling with calendar view',
      'Platform-specific content optimization',
      'Engagement analytics',
      'AI content generation',
    ],
    integrations: ['CRM Social Planner', 'Groq AI', 'CRM Contacts'],
    relatedAddons: ['content-engine', 'blog-engine', 'email-builder'],
  },
  {
    slug: 'blog-engine',
    name: 'Blog Engine',
    shortDesc: 'AI blog posts published to your CRM blog.',
    longDesc: 'Generate SEO-optimized blog posts with AI and publish them directly to your CRM-hosted blog. Supports categories, tags, featured images, and meta descriptions.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['marketing', 'content'],
    capabilities: ['blog_create', 'seo_optimize', 'category_manage', 'auto_publish'],
    requiredPlan: 'starter',
    features: [
      'AI-powered blog writing',
      'SEO optimization (meta, keywords, structure)',
      'Category and tag management',
      'Featured image support',
      'Auto-publish to CRM blog',
    ],
    integrations: ['CRM Blog', 'Groq AI'],
    relatedAddons: ['content-engine', 'social-planner', 'email-builder'],
  },
  {
    slug: 'email-builder',
    name: 'Email Builder',
    shortDesc: 'AI email campaigns and templates.',
    longDesc: 'Design and send email campaigns with AI assistance. Create templates, segment your audience, and schedule sends — all from a conversation-driven interface.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['marketing'],
    capabilities: ['email_template_create', 'email_send', 'audience_segment', 'schedule_send'],
    requiredPlan: 'starter',
    features: [
      'AI email content generation',
      'Template builder with drag-and-drop',
      'Audience segmentation',
      'Send scheduling',
      'Open and click tracking',
    ],
    integrations: ['CRM Email Builder', 'CRM Contacts', 'Groq AI'],
    relatedAddons: ['content-engine', 'campaign-manager', 'social-planner'],
  },
  {
    slug: 'campaign-manager',
    name: 'Campaign Manager',
    shortDesc: 'Manage email and SMS campaigns with analytics.',
    longDesc: 'Run multi-channel campaigns across email and SMS. Track performance, A/B test subject lines, and manage audience targeting — all in one place.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['marketing'],
    capabilities: ['campaign_create', 'audience_targeting', 'ab_testing', 'campaign_stats'],
    requiredPlan: 'starter',
    features: [
      'Email and SMS campaign management',
      'Campaign performance stats',
      'Audience targeting and segments',
      'A/B testing ready',
      'Scheduled sends',
    ],
    integrations: ['CRM Campaigns', 'CRM Contacts', 'CRM Email Builder'],
    relatedAddons: ['email-builder', 'content-engine', 'social-planner'],
  },
  {
    slug: 'funnel-builder',
    name: 'Funnel Builder',
    shortDesc: 'Manage funnels, pages, and redirects.',
    longDesc: 'Create and manage sales funnels with landing pages, thank-you pages, and redirect rules. Track conversion rates and optimize your sales process.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['marketing', 'sales'],
    capabilities: ['funnel_create', 'page_manage', 'redirect_rules', 'conversion_tracking'],
    requiredPlan: 'starter',
    features: [
      'Funnel creation and management',
      'Landing page content editing',
      'Redirect and split-test rules',
      'Conversion analytics',
      'Template library',
    ],
    integrations: ['CRM Funnels', 'CRM Contacts', 'Payment Processing'],
    relatedAddons: ['payment-processing', 'form-builder', 'campaign-manager'],
  },
  // === CRM ===
  {
    slug: 'calendar-booking',
    name: 'Calendar & Booking',
    shortDesc: 'Calendars, events, and booking links.',
    longDesc: 'Full calendar management with booking links, event scheduling, and resource allocation. Syncs with Google Calendar and lets clients book directly.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['0n-crm'],
    capabilities: ['calendar_create', 'event_manage', 'booking_links', 'resource_alloc'],
    requiredPlan: 'starter',
    features: [
      'Calendar and event management',
      'Public booking links',
      'Resource and room allocation',
      'Google Calendar sync',
      'Automated reminders',
    ],
    integrations: ['CRM Calendars', 'Google Calendar', 'CRM Contacts'],
    relatedAddons: ['contact-manager', 'opportunity-pipeline', 'phone-system'],
  },
  {
    slug: 'contact-manager',
    name: 'Contact Manager',
    shortDesc: 'Full contact CRUD with tagging and bulk operations.',
    longDesc: 'The foundation of your CRM. Create, read, update, and delete contacts with advanced tagging, custom fields, and bulk operations for managing large lists.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['0n-crm'],
    capabilities: ['contact_crud', 'tagging', 'bulk_ops', 'custom_fields'],
    requiredPlan: 'free',
    features: [
      'Full contact CRUD operations',
      'Advanced tagging system',
      'Bulk import/export',
      'Custom field management',
      'Contact search and filtering',
    ],
    integrations: ['CRM Contacts', 'CRM Custom Fields'],
    relatedAddons: ['opportunity-pipeline', 'calendar-booking', 'campaign-manager'],
  },
  {
    slug: 'opportunity-pipeline',
    name: 'Pipeline',
    shortDesc: 'Sales pipelines, stages, and deals.',
    longDesc: 'Build visual sales pipelines with customizable stages. Track deals, assign values, set close dates, and get AI-powered forecasting.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['0n-crm', 'sales'],
    capabilities: ['pipeline_create', 'deal_tracking', 'stage_manage', 'forecasting'],
    requiredPlan: 'starter',
    features: [
      'Visual pipeline builder',
      'Deal tracking with values',
      'Custom pipeline stages',
      'Drag-and-drop deal movement',
      'Revenue forecasting',
    ],
    integrations: ['CRM Opportunities', 'CRM Contacts', 'Payment Processing'],
    relatedAddons: ['contact-manager', 'payment-processing', 'invoice-automation'],
  },
  {
    slug: 'payment-processing',
    name: 'Payments',
    shortDesc: 'Process payments, orders, and subscriptions.',
    longDesc: 'Accept payments, manage orders, and handle subscriptions through your CRM. Supports one-time charges, recurring billing, and coupon codes.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['0n-crm', 'sales'],
    capabilities: ['payment_collect', 'subscription_manage', 'order_track', 'coupon_create'],
    requiredPlan: 'starter',
    features: [
      'Payment collection and processing',
      'Subscription management',
      'Order tracking and fulfillment',
      'Coupon and discount codes',
      'Payment analytics',
    ],
    integrations: ['CRM Payments', 'Stripe', 'CRM Contacts'],
    relatedAddons: ['invoice-automation', 'ecommerce-store', 'opportunity-pipeline'],
  },
  {
    slug: 'invoice-automation',
    name: 'Invoice Automation',
    shortDesc: 'AI invoices, estimates, and recurring billing.',
    longDesc: 'Generate professional invoices with AI, send estimates, and set up recurring billing. Auto-reminders ensure you get paid on time.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['0n-crm'],
    capabilities: ['invoice_create', 'estimate_send', 'recurring_billing', 'auto_reminders'],
    requiredPlan: 'starter',
    features: [
      'AI-powered invoice generation',
      'Estimate and quote creation',
      'Recurring billing automation',
      'Auto-payment reminders',
      'PDF export and email delivery',
    ],
    integrations: ['CRM Invoices', 'CRM Contacts', 'Payment Processing'],
    relatedAddons: ['payment-processing', 'contact-manager', 'opportunity-pipeline'],
  },
  {
    slug: 'location-settings',
    name: 'Location Settings',
    shortDesc: 'Custom fields, values, tags, and templates.',
    longDesc: 'Configure your CRM location with custom fields, values, tags, and templates. The control center for your CRM configuration.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['0n-crm', 'admin'],
    capabilities: ['custom_fields', 'custom_values', 'tag_manage', 'template_config'],
    requiredPlan: 'free',
    features: [
      'Custom field creation and management',
      'Custom values and variables',
      'Tag organization',
      'Template configuration',
      'Location-level settings',
    ],
    integrations: ['CRM Locations', 'CRM Custom Fields'],
    relatedAddons: ['contact-manager', 'user-management', 'custom-objects'],
  },
  // === COMMUNICATION ===
  {
    slug: 'phone-system',
    name: 'Phone System',
    shortDesc: 'Purchase phone numbers and manage voice lines.',
    longDesc: 'Purchase and manage phone numbers directly in your CRM. Set up call forwarding, recording, and voicemail — all integrated with your contact records.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['communication'],
    capabilities: ['number_purchase', 'call_forwarding', 'call_recording', 'voicemail'],
    requiredPlan: 'starter',
    features: [
      'Phone number purchasing',
      'Call forwarding and routing',
      'Call recording and playback',
      'Voicemail configuration',
      'CRM contact auto-linking',
    ],
    integrations: ['CRM Phone', 'CRM Contacts', 'CRM Conversations'],
    relatedAddons: ['voice-ai-agent', 'conversation-ai', 'contact-manager'],
  },
  {
    slug: 'document-contracts',
    name: 'Documents',
    shortDesc: 'Contracts and proposals with e-signature.',
    longDesc: 'Send contracts, proposals, and documents for e-signature. Track document status, use templates, and auto-fill from CRM contact data.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['communication', 'sales'],
    capabilities: ['contract_send', 'template_manage', 'esignature', 'doc_tracking'],
    requiredPlan: 'starter',
    features: [
      'Contract and proposal sending',
      'E-signature collection',
      'Template library',
      'Auto-fill from CRM data',
      'Document status tracking',
    ],
    integrations: ['CRM Documents', 'CRM Contacts'],
    relatedAddons: ['invoice-automation', 'opportunity-pipeline', 'contact-manager'],
  },
  {
    slug: 'form-builder',
    name: 'Form Builder',
    shortDesc: 'Forms, surveys, and submission tracking.',
    longDesc: 'Create forms and surveys that feed directly into your CRM. Track submissions, trigger automations on form fill, and segment leads by response.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['content', 'communication'],
    capabilities: ['form_create', 'survey_build', 'submission_track', 'automation_trigger'],
    requiredPlan: 'starter',
    features: [
      'Drag-and-drop form creation',
      'Survey builder with logic',
      'Submission tracking and export',
      'Automation triggers on submit',
      'CRM contact auto-creation',
    ],
    integrations: ['CRM Forms', 'CRM Contacts', 'CRM Workflows'],
    relatedAddons: ['funnel-builder', 'contact-manager', 'campaign-manager'],
  },
  // === SALES ===
  {
    slug: 'affiliate-manager',
    name: 'Affiliate Manager',
    shortDesc: 'Affiliate programs with commission tracking.',
    longDesc: 'Launch and manage affiliate programs. Onboard affiliates, track referrals, manage commissions, and generate referral links — all within your CRM.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['sales'],
    capabilities: ['affiliate_onboard', 'commission_track', 'referral_links', 'payout_manage'],
    requiredPlan: 'professional',
    features: [
      'Affiliate onboarding portal',
      'Commission tracking and tiers',
      'Referral link generation',
      'Payout management',
      'Performance dashboards',
    ],
    integrations: ['CRM Affiliates', 'CRM Contacts', 'Payment Processing'],
    relatedAddons: ['payment-processing', 'ecommerce-store', 'product-catalog'],
  },
  {
    slug: 'product-catalog',
    name: 'Product Catalog',
    shortDesc: 'Products, pricing, and collections.',
    longDesc: 'Manage your product catalog with pricing tiers, collections, and variants. Connects to your store, invoices, and payment processing.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['sales'],
    capabilities: ['product_crud', 'price_manage', 'collection_organize', 'variant_support'],
    requiredPlan: 'starter',
    features: [
      'Product CRUD operations',
      'Price and tier management',
      'Collection organization',
      'Variant support',
      'Inventory tracking',
    ],
    integrations: ['CRM Products', 'Payment Processing', 'E-Commerce Store'],
    relatedAddons: ['ecommerce-store', 'payment-processing', 'invoice-automation'],
  },
  {
    slug: 'ecommerce-store',
    name: 'E-Commerce',
    shortDesc: 'Store settings, shipping, and fulfillment.',
    longDesc: 'Full e-commerce capabilities within your CRM. Configure store settings, manage shipping rules, and track fulfillment from order to delivery.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['sales'],
    capabilities: ['store_config', 'shipping_rules', 'fulfillment_track', 'order_manage'],
    requiredPlan: 'professional',
    features: [
      'Store configuration and branding',
      'Shipping rules and zones',
      'Order fulfillment tracking',
      'Inventory management',
      'Customer notifications',
    ],
    integrations: ['CRM E-Commerce', 'Payment Processing', 'Product Catalog'],
    relatedAddons: ['product-catalog', 'payment-processing', 'affiliate-manager'],
  },
  // === CONTENT ===
  {
    slug: 'media-manager',
    name: 'Media Manager',
    shortDesc: 'Upload and organize media assets.',
    longDesc: 'Central media library for all your images, videos, and files. Organize with folders, search by name, and use across all your CRM content.',
    price: 900,
    priceLabel: '$9/mo',
    categories: ['content'],
    capabilities: ['file_upload', 'folder_manage', 'asset_organize', 'media_search'],
    requiredPlan: 'free',
    features: [
      'Drag-and-drop file upload',
      'Folder organization',
      'Asset tagging and search',
      'Image optimization',
      'Cross-platform usage',
    ],
    integrations: ['CRM Media', 'CRM Blog', 'CRM Email Builder'],
    relatedAddons: ['blog-engine', 'email-builder', 'brand-board'],
  },
  {
    slug: 'wordpress-manager',
    name: 'WordPress',
    shortDesc: 'Manage connected WordPress sites.',
    longDesc: 'Connect and manage your WordPress sites directly from your CRM. Monitor status, sync content, and manage plugins from one dashboard.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['content', 'admin'],
    capabilities: ['site_manage', 'status_monitor', 'content_sync', 'plugin_manage'],
    requiredPlan: 'starter',
    features: [
      'WordPress site management',
      'Status monitoring and alerts',
      'Content synchronization',
      'Plugin management',
      'Multi-site support',
    ],
    integrations: ['CRM WordPress', 'CRM Blog'],
    relatedAddons: ['blog-engine', 'media-manager', 'brand-board'],
  },
  {
    slug: 'brand-board',
    name: 'Brand Board',
    shortDesc: 'Brand design kits and assets.',
    longDesc: 'Create and manage your brand identity in one place. Colors, fonts, logos, and design guidelines — all accessible across your CRM content.',
    price: 900,
    priceLabel: '$9/mo',
    categories: ['content'],
    capabilities: ['brand_kit', 'color_manage', 'font_select', 'logo_manage'],
    requiredPlan: 'free',
    features: [
      'Brand kit creation',
      'Color palette management',
      'Font selection and pairing',
      'Logo management and versions',
      'Design guideline documentation',
    ],
    integrations: ['CRM Brand', 'CRM Media'],
    relatedAddons: ['media-manager', 'email-builder', 'funnel-builder'],
  },
  // === ADMIN ===
  {
    slug: 'snapshot-manager',
    name: 'Snapshot Manager',
    shortDesc: 'Generate, deploy, and clone CRM snapshots.',
    longDesc: 'Create full backups of your CRM configuration and deploy them to new locations. Clone entire setups, share templates, and manage versioned snapshots.',
    price: 9900,
    priceLabel: '$99/mo',
    categories: ['admin'],
    capabilities: ['snapshot_create', 'snapshot_deploy', 'cross_location_clone', 'version_manage'],
    requiredPlan: 'professional',
    badge: 'Pro',
    features: [
      'Full CRM backup snapshots',
      'Cross-location cloning',
      'One-click deployment',
      'Version management',
      'Template sharing',
    ],
    integrations: ['CRM Snapshots', 'CRM Locations'],
    relatedAddons: ['saas-manager', 'location-settings', 'custom-objects'],
  },
  {
    slug: 'workflow-reader',
    name: 'Workflow Intelligence',
    shortDesc: 'Read workflows and export as .0n SWITCH files.',
    longDesc: 'Analyze your existing CRM workflows, understand their logic, and export them as portable .0n SWITCH files. Make your automations portable and version-controlled.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['admin', 'ai-automation'],
    capabilities: ['workflow_read', 'workflow_analyze', 'switch_export', 'portability'],
    requiredPlan: 'starter',
    features: [
      'Workflow analysis and visualization',
      '.0n SWITCH file export',
      'Automation portability',
      'Cross-location workflow transfer',
      'Version control support',
    ],
    integrations: ['CRM Workflows', '0n-spec', '0nMCP SDK'],
    relatedAddons: ['agent-studio', 'snapshot-manager', 'link-triggers'],
  },
  {
    slug: 'custom-objects',
    name: 'Custom Objects',
    shortDesc: 'Custom schemas, records, and associations.',
    longDesc: 'Extend your CRM with custom data models. Create schemas, manage records, and build associations between any objects in your system.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['admin'],
    capabilities: ['schema_create', 'record_crud', 'association_manage', 'field_define'],
    requiredPlan: 'professional',
    features: [
      'Custom schema creation',
      'Record CRUD operations',
      'Object associations and relationships',
      'Custom field definitions',
      'API access for custom objects',
    ],
    integrations: ['CRM Objects', 'CRM Contacts', 'CRM Workflows'],
    relatedAddons: ['location-settings', 'contact-manager', 'snapshot-manager'],
  },
  {
    slug: 'user-management',
    name: 'User Management',
    shortDesc: 'Team members, roles, and permissions.',
    longDesc: 'Manage your team within the CRM. Create users, assign roles, set permissions, and control access to features and data.',
    price: 1900,
    priceLabel: '$19/mo',
    categories: ['admin'],
    capabilities: ['user_crud', 'role_assign', 'permission_set', 'access_control'],
    requiredPlan: 'starter',
    features: [
      'User creation and management',
      'Role-based access control',
      'Permission granularity',
      'Team organization',
      'Activity logging',
    ],
    integrations: ['CRM Users', 'CRM Locations'],
    relatedAddons: ['location-settings', 'saas-manager', 'snapshot-manager'],
  },
  {
    slug: 'saas-manager',
    name: 'SaaS Manager',
    shortDesc: 'Manage SaaS locations and white-label.',
    longDesc: 'The ultimate admin tool for agencies. Provision new SaaS locations, configure white-label branding, and manage company settings across your entire portfolio.',
    price: 9900,
    priceLabel: '$99/mo',
    categories: ['admin'],
    capabilities: ['location_provision', 'whitelabel_config', 'company_settings', 'portfolio_manage'],
    requiredPlan: 'unlimited',
    badge: 'Pro',
    features: [
      'SaaS location provisioning',
      'White-label branding',
      'Company settings management',
      'Multi-location portfolio',
      'Client onboarding automation',
    ],
    integrations: ['CRM SaaS', 'CRM Locations', 'CRM Company'],
    relatedAddons: ['snapshot-manager', 'user-management', 'location-settings'],
  },
  // === ANALYTICS ===
  {
    slug: 'link-triggers',
    name: 'Link Triggers',
    shortDesc: 'Trigger links for workflow automation.',
    longDesc: 'Create trackable links that trigger CRM workflows when clicked. Perfect for email campaigns, SMS messages, and social posts.',
    price: 900,
    priceLabel: '$9/mo',
    categories: ['analytics', 'admin'],
    capabilities: ['link_create', 'trigger_automation', 'click_tracking', 'utm_manage'],
    requiredPlan: 'free',
    features: [
      'Trigger link creation',
      'Click-based automation triggers',
      'Click tracking and analytics',
      'UTM parameter management',
      'Redirect customization',
    ],
    integrations: ['CRM Links', 'CRM Workflows', 'CRM Contacts'],
    relatedAddons: ['workflow-reader', 'campaign-manager', 'funnel-builder'],
  },
  {
    slug: 'detect-and-refine',
    name: 'Detect & Refine',
    shortDesc: 'Closed-loop ad optimization. Grade every click A+ → F, fan the offline conversion back to whichever ad network sent it.',
    longDesc: 'Detect & Refine watches every visitor — scroll depth, mouse velocity, rage clicks, dwell, exit intent — and grades the click A+ → F with rule-based scoring refined by Groq AI. Then it fans the offline conversion signal back to Google Ads, Meta, LinkedIn, TikTok, and X automatically, so the networks learn who to bid on (and who to stop showing ads to). 4 KB embed, sendBeacon, auto-captures gclid/fbclid/li_fat_id/ttclid/twclid. Per-tenant accounts with allowed_origins gating, monthly quotas, and audit-logged conversion sends. Ships as 15 tools inside 0nMCP — installable via `npm i 0nmcp` and configured through dr_account_create + dr_account_update. Or use the standalone REST surface at detect-and-refine-cryptogoatz.vercel.app.',
    price: 4900,
    priceLabel: '$49/mo',
    categories: ['analytics', 'ai-automation'],
    capabilities: [
      'behavioral_track',
      'click_grade_ai',
      'ad_network_fanout',
      'tenant_accounts',
      'origin_allowlist',
      'monthly_quota',
      'sheet_export',
      'rollup_stats',
    ],
    requiredPlan: 'starter',
    badge: 'NEW',
    features: [
      '4 KB tracking script — non-blocking, async, sendBeacon',
      'Auto-captures gclid, fbclid, li_fat_id, ttclid, twclid',
      '30+ behavioral signals: scroll, dwell, rage/dead clicks, form focus, tab visibility',
      'Rule-based scoring refined by Groq llama-3.1-8b',
      'Grades A+ → F (sale, nurture, dead, exclude)',
      'Offline conversion fanout: Google Ads OCI, Meta CAPI, LinkedIn, TikTok, X',
      'Per-tenant accounts with origin allowlist + monthly quota',
      'Audit log of every network conversion send',
      'Adaptive Siphon — live canvas of traffic quality',
      'Install via 0nMCP (15 tools) or REST API',
    ],
    integrations: ['Google Ads', 'Meta Ads', 'LinkedIn Ads', 'TikTok Ads', 'X Ads', 'Google Sheets', 'Groq AI', '0nMCP'],
    relatedAddons: ['link-triggers', 'campaign-manager', 'funnel-builder', 'cro9', 'rocketpost', 'rocket-convert'],
  },
  {
    slug: 'cro9',
    name: 'CRO9 — Conversion Optimization',
    shortDesc: 'AI-driven conversion-rate optimization. Auto-tests headlines, colors, copy, and layout. Picks winners with bandit math.',
    longDesc: 'CRO9 is the optimization engine that learns which version of your form, page, or product converts best — without manual A/B test setup. Drop the embed once and CRO9 generates variants via Groq, runs Thompson-sampling bandits to allocate traffic, measures conversion rate against real submissions, and retires losers automatically. Ships standalone (use it on any existing form/page) or paired with Rocket Convert (the form + landing-page builder that ships variants for free) and Detect & Refine (which filters out bot/dead traffic before the bandit sees it). Composes with the Rocket Convert form-variant tools today; landing-page-variant tools land in the next sprint.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['analytics', 'ai-automation'],
    capabilities: [
      'variant_generate_ai',
      'bandit_picker',
      'conversion_attribution',
      'seo_neuro_engine',
      'auto_optimize',
      'living_dom',
    ],
    requiredPlan: 'starter',
    badge: 'OPTIMIZER',
    features: [
      'AI generates A/B variants via Groq (headlines, CTAs, colors, copy)',
      'Thompson-sampling bandit allocates traffic to winners',
      'Living DOM — variant swap with no page reload',
      'Conversion attribution per variant per session',
      'SEO neuro engine — adaptive weights per task family',
      'Composes with Detect & Refine to ignore bad traffic in attribution',
      'Standalone embed or paired with Rocket Convert',
    ],
    integrations: ['Detect & Refine', 'Rocket Convert', 'Groq AI', '0nMCP', 'CRM'],
    relatedAddons: ['detect-and-refine', 'rocket-convert', 'rocketpost'],
  },
  {
    slug: 'rocketpost',
    name: 'RocketPost — Forms + Email Sequences',
    shortDesc: 'AI generates the form, AI drafts the email sequence, and one embed code does the rest.',
    longDesc: 'RocketPost is the simplest version of the unified product: tell the AI your goal ("capture demo requests for a B2B SaaS"), get a form with the right fields, headline, and CTA, plus a 3-step email follow-up sequence. Paste one script tag on any page and it renders the form, captures submissions, and enrolls subscribers automatically. Sequences sync to your CRM workflow (when bound) so the same logic runs in the place your sales team already lives. Ships as Tier 1 of Rocket Convert — buy this if you only want forms + email; upgrade to Rocket Convert for the landing-page and commerce tiers.',
    price: 2900,
    priceLabel: '$29/mo',
    categories: ['marketing', 'content'],
    capabilities: [
      'form_create_ai',
      'form_publish',
      'email_sequence_ai',
      'sequence_enroll',
      'crm_workflow_sync',
      'submission_capture',
    ],
    requiredPlan: 'starter',
    badge: 'NEW',
    features: [
      'AI generates form fields + headline + CTA from a goal',
      'AI drafts 3-step email follow-up sequence',
      'One embed snippet renders form + handles submission',
      'Honeypot + uuid validation built in',
      'Sequences sync to CRM workflows',
      'CSV export of submissions',
      'Pairs with Detect & Refine for bot filtering',
      'Upgrade to Rocket Convert for landing pages + commerce',
    ],
    integrations: ['CRM Workflows', 'CRM Contacts', 'Detect & Refine', 'CRO9', 'Groq AI', '0nMCP'],
    relatedAddons: ['rocket-convert', 'cro9', 'detect-and-refine', 'form-builder'],
  },
  {
    slug: 'rocket-convert',
    name: 'Rocket Convert — Forms + Pages + Commerce',
    shortDesc: 'The unified conversion suite. Forms today. AI landing pages and commerce checkout next sprint. CRO9 + Detect & Refine baked in.',
    longDesc: 'Rocket Convert is the three-tier unified product that ships RocketPost (forms + email), CRO9 (variant testing), and Detect & Refine (bot/dead-traffic filtering) under one embed and one bill. Tier 1 (live now): AI-generated forms with email follow-up + bandit-driven variant testing. Tier 2 (next sprint): AI-generated landing pages where CRO9 tests headlines, colors, layouts, and copy in real time and DR removes bad traffic. Tier 3 (after that): commerce — drop a Stripe or PayPal product onto a page and CRO9 starts optimizing the product copy, price points, and checkout flow. One script tag, three tiers, all the optimization happens automatically. Each tier also available standalone — RocketPost for forms-only, CRO9 for variants-only, Detect & Refine for ad-traffic grading-only.',
    price: 9900,
    priceLabel: '$99/mo',
    categories: ['marketing', 'analytics', 'ai-automation'],
    capabilities: [
      'form_create_ai',
      'form_variants_ai',
      'bandit_optimization',
      'email_sequence_ai',
      'landing_page_ai',
      'commerce_checkout',
      'detect_refine_integrated',
      'cro9_integrated',
    ],
    requiredPlan: 'professional',
    badge: 'FEATURED',
    features: [
      'Tier 1 — AI form builder + 3-step nurture (live)',
      'Tier 2 — AI landing pages with live A/B (next sprint)',
      'Tier 3 — Stripe/PayPal product pages with auto-optimized copy',
      'CRO9 bandit picks winning variants automatically',
      'Detect & Refine grades every submitter A+ → F',
      'Bot traffic filtered before it hits your bandit math',
      'Conversions stream to Google Ads, Meta, LinkedIn, TikTok, X',
      'CRM workflow sync for sequences',
      'One embed, three tiers',
    ],
    integrations: ['Stripe', 'PayPal', 'Google Ads', 'Meta Ads', 'LinkedIn Ads', 'CRM Workflows', 'CRO9', 'Detect & Refine', 'Groq AI', '0nMCP'],
    relatedAddons: ['rocketpost', 'cro9', 'detect-and-refine', 'funnel-builder', 'campaign-manager'],
  },
]

export function getAddonsByCategory(categorySlug: string): MarketplaceAddon[] {
  if (categorySlug === 'all') return ADDONS
  return ADDONS.filter(a => a.categories.includes(categorySlug))
}

export function getAddonBySlug(slug: string): MarketplaceAddon | undefined {
  return ADDONS.find(a => a.slug === slug)
}

export function getCategoryBySlug(slug: string): MarketplaceCategory | undefined {
  return CATEGORIES.find(c => c.slug === slug)
}

export function getRelatedAddons(addon: MarketplaceAddon): MarketplaceAddon[] {
  return addon.relatedAddons
    .map(slug => ADDONS.find(a => a.slug === slug))
    .filter((a): a is MarketplaceAddon => !!a)
}
