export const metadata = {
  title: 'Privacy Policy — 0n Course Builder',
  alternates: { canonical: 'https://www.0ncore.com/course-builder/privacy' },
}

/** A reviewer opens this. A 404 here is a standard rejection. */
export default function Page() {
  return (
    <main className="min-h-screen bg-[#0d1117] px-6 py-16 text-[#f0f4f8]">
      <article className="mx-auto max-w-2xl">
        <h1 className="text-3xl font-black">Privacy Policy</h1>
        <p className="mt-2 text-[13px] text-[#6b7c9c]">0n Course Builder · RocketOpp LLC · Updated 15 August 2026</p>

        <H>What this app accesses</H>
        <P>0n Course Builder is installed into a CRM sub-account. With your permission it reads the account
        identifier it was opened from, and writes courses and lessons you generate into that account&apos;s course area.
        It does not read your contacts, conversations, calendars or payment data.</P>

        <H>What we store</H>
        <P>The topic and audience you type, the generated course content, and a record of each publish so you can
        see what was created and when. We store the account identifier so a course lands in the right place.</P>

        <H>What we never store</H>
        <P>We do not store your CRM password. Access tokens are held encrypted and are used only to publish the
        course you asked for. We do not sell data, and we do not use your course content to train models.</P>

        <H>AI processing</H>
        <P>Course text is generated by third-party language-model providers. Your topic and audience are sent to
        them to produce the lessons. Nothing else from your CRM is sent.</P>

        <H>Deleting your data</H>
        <P>Uninstalling the app revokes our access immediately. Email <A href="mailto:mike@rocketopp.com">mike@rocketopp.com</A> to
        have stored course records deleted, and we will confirm within 30 days.</P>

        <H>Contact</H>
        <P>RocketOpp LLC · <A href="mailto:mike@rocketopp.com">mike@rocketopp.com</A></P>
      </article>
    </main>
  )
}

function H({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-8 text-lg font-bold">{children}</h2>
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-2 leading-relaxed text-[#9fb0cc]">{children}</p>
}
function A({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} className="text-[#7ED957] hover:underline">{children}</a>
}
